const locations = [
  "Lahore, Punjab",
  "Karachi, Sindh",
  "Islamabad",
  "Multan, Punjab",
  "Peshawar, Khyber Pakhtunkhwa",
  "Quetta, Balochistan",
  "Hyderabad, Sindh",
  "Sialkot, Punjab",
  "Faisalabad, Punjab",
  "Rawalpindi, Punjab",
  "Gujranwala, Punjab",
  "Sukkur, Sindh",
  "Lahore, Punjab",
  "Karachi, Sindh",
  "Islamabad",
  "Multan, Punjab",
  "Peshawar, Khyber Pakhtunkhwa",
  "Quetta, Balochistan",
  "Hyderabad, Sindh",
  "Sialkot, Punjab",
  "Faisalabad, Punjab",
  "Rawalpindi, Punjab",
  "Gujranwala, Punjab",
  "Sukkur, Sindh",
  "Lahore, Punjab",
  "Karachi, Sindh",
  "Islamabad",
  "Multan, Punjab",
  "Peshawar, Khyber Pakhtunkhwa",
  "Quetta, Balochistan",
  "Hyderabad, Sindh",
  "Sialkot, Punjab",
  "Faisalabad, Punjab",
  "Rawalpindi, Punjab",
  "Gujranwala, Punjab",
  "Sukkur, Sindh",
  "Lahore, Punjab",
  "Karachi, Sindh",
  "Islamabad",
  "Multan, Punjab",
  "Peshawar, Khyber Pakhtunkhwa",
  "Quetta, Balochistan",
  "Hyderabad, Sindh",
  "Sialkot, Punjab",
  "Faisalabad, Punjab",
  "Rawalpindi, Punjab",
  "Gujranwala, Punjab",
  "Sukkur, Sindh",
  "Lahore, Punjab",
  "Karachi, Sindh",
  "Islamabad",
  "Multan, Punjab",
  "Peshawar, Khyber Pakhtunkhwa",
  "Quetta, Balochistan",
  "Hyderabad, Sindh",
  "Sialkot, Punjab",
  "Faisalabad, Punjab",
  "Rawalpindi, Punjab",
  "Gujranwala, Punjab",
  "Sukkur, Sindh",
  "Lahore, Punjab",
  "Karachi, Sindh",
  "Islamabad",
  "Multan, Punjab",
  "Peshawar, Khyber Pakhtunkhwa",
  "Quetta, Balochistan",
  "Hyderabad, Sindh",
  "Sialkot, Punjab",
  "Faisalabad, Punjab",
  "Rawalpindi, Punjab",
  "Gujranwala, Punjab",
  "Sukkur, Sindh",
  "Lahore, Punjab",
  "Karachi, Sindh",
  "Islamabad",
  "Multan, Punjab",
  "Peshawar, Khyber Pakhtunkhwa",
  "Quetta, Balochistan",
  "Hyderabad, Sindh",
  "Sialkot, Punjab",
  "Faisalabad, Punjab",
  "Rawalpindi, Punjab",
  "Gujranwala, Punjab",
  "Sukkur, Sindh",
  "Lahore, Punjab",
  "Karachi, Sindh",
  "Islamabad",
  "Multan, Punjab",
  "Peshawar, Khyber Pakhtunkhwa",
  "Quetta, Balochistan",
  "Hyderabad, Sindh",
  "Sialkot, Punjab",
  "Faisalabad, Punjab",
  "Rawalpindi, Punjab",
  "Gujranwala, Punjab",
  "Sukkur, Sindh",
  "Lahore, Punjab",
  "Karachi, Sindh",
  "Islamabad",
  "Multan, Punjab",
  "Peshawar, Khyber Pakhtunkhwa",
  "Quetta, Balochistan",
  "Hyderabad, Sindh",
  "Sialkot, Punjab",
  "Faisalabad, Punjab",
  "Rawalpindi, Punjab",
  "Gujranwala, Punjab",
  "Sukkur, Sindh",
  "Lahore, Punjab",
  "Karachi, Sindh",
  "Islamabad",
  "Multan, Punjab",
  "Peshawar, Khyber Pakhtunkhwa",
  "Quetta, Balochistan",
  "Hyderabad, Sindh",
  "Sialkot, Punjab",
  "Faisalabad, Punjab",
  "Rawalpindi, Punjab",
  "Gujranwala, Punjab",
  "Sukkur, Sindh",
  "Lahore, Punjab",
  "Karachi, Sindh",
  "Islamabad",
  "Multan, Punjab",
  "Peshawar, Khyber Pakhtunkhwa",
  "Quetta, Balochistan",
  "Hyderabad, Sindh",
  "Sialkot, Punjab",
  "Faisalabad, Punjab",
  "Rawalpindi, Punjab",
  "Gujranwala, Punjab",
  "Sukkur, Sindh",
  "Lahore, Punjab"
];

export default locations;